# Generated by Django 2.0.7 on 2018-07-17 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the available location', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_needed', models.IntegerField(help_text='Enter time needed to complete delivery. eg (40 = > 40 minutes)')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodMax.Coverage')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Menu Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Enter the name of the menu', max_length=200)),
                ('cover_image', models.ImageField(help_text='Upload menu cover image', upload_to='menu_cover_images/%Y/%m/%d/')),
                ('description', models.TextField(help_text='Enter menu description', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Restaurant Id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the restaurant', max_length=200)),
                ('tag_line', models.CharField(blank=True, help_text='Enter your restaurant tag line', max_length=220)),
                ('email', models.EmailField(blank=True, help_text='Enter the restaurant email to receive orders', max_length=254)),
                ('cover_image', models.ImageField(help_text='Upload restaurant cover image', upload_to='restaurant_cover_images/%Y/%m/%d/')),
                ('logo', models.ImageField(help_text='Upload restaurant logo', upload_to='restaurant_logos/%Y/%m/%d/')),
                ('minimum_food_amount', models.IntegerField(help_text='Enter the minimum food amount')),
                ('description', models.TextField(help_text='Enter the description of the restaurant', max_length=1000)),
                ('address', models.CharField(help_text='Enter the address of the restaurant', max_length=100)),
                ('coverage', models.ManyToManyField(through='FoodMax.CoverageDetail', to='FoodMax.Coverage')),
                ('menu', models.ManyToManyField(to='FoodMax.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the dish name', max_length=300)),
                ('price', models.IntegerField(help_text='Enter the price of the dish')),
                ('dish_image', models.ImageField(help_text='Upload dish cover image', upload_to='dish_images/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
        migrations.AddField(
            model_name='coveragedetail',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodMax.Restaurant'),
        ),
    ]
