# Generated by Django 2.0.7 on 2018-07-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0002_auto_20180709_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the menu', max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coverage',
            field=models.ManyToManyField(to='FoodMax.Coverage'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='FoodMax.Menu'),
        ),
    ]
