# Generated by Django 2.0.7 on 2018-07-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0003_auto_20180709_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='price',
            field=models.DecimalField(decimal_places='2', help_text='Enter the price of the dish', max_digits='10'),
        ),
    ]
