# Generated by Django 2.0.7 on 2018-07-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0005_auto_20180712_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='minimum_food_amount',
            field=models.IntegerField(help_text='Enter the minimum food amount'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='price',
            field=models.IntegerField(help_text='Enter the price of the dish'),
        ),
    ]
