# Generated by Django 2.0.7 on 2018-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0006_auto_20180712_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the restaurant email to receive orders', max_length=254),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
    ]
