# Generated by Django 2.0.7 on 2018-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0007_auto_20180714_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tag_line',
            field=models.CharField(blank=True, help_text='Enter your restaurant tag line', max_length=220),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
    ]
