# Generated by Django 2.0.7 on 2018-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0009_auto_20180714_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coverage',
            field=models.ManyToManyField(to='FoodMax.Coverage'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
    ]
