# Generated by Django 2.0.7 on 2018-07-14 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FoodMax', '0010_auto_20180714_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Coverage Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(to='FoodMax.Submenu'),
        ),
    ]
